apiVersion: v1
kind: Namespace
metadata:
  name: tinyllamax
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    policy.tinyllamax.io/enforce-signatures: "true"
    policy.tinyllamax.io/enforce-nonroot: "true"
    policy.tinyllamax.io/enforce-readonly-fs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tinyllamax-staging
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
    policy.tinyllamax.io/enforce-signatures: "true"
    policy.tinyllamax.io/enforce-nonroot: "true"
    policy.tinyllamax.io/enforce-readonly-fs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tinyllamax-dev
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
    policy.tinyllamax.io/enforce-signatures: "false"
    policy.tinyllamax.io/enforce-nonroot: "true"
    policy.tinyllamax.io/enforce-readonly-fs: "false"
